# coding=utf-8
# Copyright ©2024 ZHJ. All Rights Reserved.
# Beta 3
FOR = ['FilesChecker Beta', 3.0, 'Windows']
LANGUAGE = ['Chinese__Traditional__Taiwan', '繁體中文 (中國臺灣)']
def s1():
    return '文件校驗器 Beta'
def s2():
    return '開始校驗(&K)'
def s3():
    return '添加文件(&F)…'
def s4():
    return '添加雜湊值(&H)…'
def s5():
    return '導入任務列表(&O)…'
def s6():
    return '保存任務列表(&S)…'
def s7():
    return '匯出校驗結果(&E)…'
def s8():
    return '清空列表(&C)'
def s9():
    return '設置(&S)…'
def s10():
    return '退出(&X)'
def s11():
    return '任務(&T)'
def s12():
    return '關於(&A)…'
def s13():
    return '幫助(&H)'
def s14():
    return '添加文件(&F)…'
def s15():
    return '添加雜湊值(&H)…'
def s16():
    return '開始校驗(&K)'
def s17():
    return '序號'
def s18():
    return '組號'
def s19():
    return '文件'
def s20():
    return '雜湊值'
def s21():
    return '自動'
def s22():
    return '添加文件'
def s23():
    return '所有檔案 (*.*)|*.*'
def s24():
    return '設置'
def s25():
    return '完成後操作'
def s26():
    return '無'
def s27():
    return '關機'
def s28():
    return '重啟'
def s29():
    return '自訂…'
def s30():
    return '自動保存校驗結果'
def s31():
    return '自動保存校驗結果'
def s32():
    return '匯出校驗結果'
def s33():
    return 'Microsoft Excel 逗號分隔值文件 (*.csv)|*.csv|文字文件 (*.txt)|*.txt|所有檔案 (*.*)|*.*'
def s34():
    return '常規'
def s35():
    return '語言設置'
def s36():
    return '雜湊數值型別：'
def s37():
    return '應用(&A)'
def s38():
    return '刪除(&D)'
def s39():
    return '需要重新開機軟體以更改語言。你確定要繼續嗎？'
def s40():
    return '語言'
def s41():
    return '添加雜湊值…'
def s42():
    return '添加雜湊值'
def s43():
    return '未知'
def s44():
    return '關於'
def s45():
    return '文件校驗器 v3.0 Beta3'
def s46():
    return '未安裝該語言包。'
def s47(pyver, wxver):
    return 'Python 版本：' + pyver + '    wxPython 版本：' + wxver
def s48():
    return '文字文件 (*.txt)|*.txt|所有檔案 (*.*)|*.*'
def s49():
    return '導入任務列表'
def s50():
    return '打開文本文檔'
def s51():
    return '請選擇文本文檔使用的編碼。'
def s52():
    return '預覽：'
def s53():
    return '確定'
def s54():
    return '取消'
def s55():
    return '無法讀取文件：'
def s56():
    return '無法讀取任務列表：'
def s57():
    return '確定(&O)'
def s58():
    return '任務清單錯誤：不支援的演算法。'
def s59():
    return '任務清單錯誤：未定義資料類型。'
def s60():
    return '保存任務列表'
def s61():
    return '任務清單中不含任何可添加資料。'
def s62():
    return '警告'
def s63():
    return '是(&Y)'
def s64():
    return '否(&N)'
def s65():
    return '正在校驗，確認退出？'
def s66():
    return '已用時間：'
def s67():
    return '已處理：'
def s68():
    return '進度：'
def s69():
    return '總進度：'
def s70():
    return '雜湊值計算'
def s71():
    return '正在處理：'
def s72():
    return '大小：'
def s73():
    return '位元組'
def s74():
    return '時間：'
def s75(err):
    return '發生錯誤，以下是錯誤資訊：\n' + err
def s76():
    return '顯示詳細資訊(&S)'
def s77():
    return '重新選擇檔(&C)…'
def s78():
    return '編輯雜湊值(&E)…'
def s79():
    return '複製檔地址(&F)'
def s80():
    return '複製雜湊值(&H)'
def s81():
    return '錯誤'
def s82():
    return '正在計算雜湊值…'
def s83():
    return '正在校驗…'
def s84():
    return '正在保存校驗結果：'
def s85():
    return '正在運行命令：'
def s86():
    return '正在保存任務列表：'
def s87():
    return '重新選擇檔'
def s88():
    return '編輯雜湊值'
def s89():
    return '已複製到剪貼板。'
def s90():
    return '運行命令：'
def s91():
    return '設置項"自動保存校驗結果"無效。'
def s92():
    return '詳細資訊'
def s93():
    return '文件：'
def s94():
    return '雜湊值：'
def s95():
    return '計算耗時：'
def s96():
    return '錯誤資訊：'
def s97():
    return '計算雜湊值並校驗。'
def s98():
    return '添加一個或多個檔。'
def s99():
    return '添加雜湊值。'
def s100():
    return '從檔載入任務列表。'
def s101():
    return '將任務列表保存到檔。'
def s102():
    return '將校驗結果匯出到檔。'
def s103():
    return '更改軟體的設置。'
def s104():
    return '退出本軟體。'
def s105():
    return '顯示軟體資訊、版本號和版權。'
