; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId=FilesChecker
AppName={cm:MyAppName}
AppVersion=4.0
;AppVerName=FilesChecker 4.0
AppPublisher=ZHJ
AppPublisherURL=https://github.com/ZHJ00000/
AppSupportURL=https://github.com/ZHJ00000/FilesChecker/wiki
AppUpdatesURL=https://github.com/ZHJ00000/FilesChecker/releases
DefaultDirName={autopf}\FilesChecker3
UninstallDisplayIcon={app}\FilesChecker.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=LICENSE.txt
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=FilesCheckerUpdate_3.1.2_4.0_amd64
Compression=lzma
SolidCompression=yes
WizardStyle=modern
AppCopyright=Copyright ©2025 ZHJ.
MinVersion=10.0.10240
VersionInfoCompany=ZHJ
VersionInfoDescription=FilesChecker
VersionInfoProductName=FilesChecker
VersionInfoVersion=4.0
UninstallDisplayName={cm:MyAppName}
Password=67N8F-38W0A-RNI22-YX1AQ-11AZ5

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
Name: "chinesetraditional"; MessagesFile: "compiler:Languages\ChineseTraditional.isl"

[CustomMessages]
english.MyAppName=FilesChecker
chinesesimplified.MyAppName=文件校验器
chinesetraditional.MyAppName=文件校驗器

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Source: "Update3.1.2\FilesChecker.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "Update3.1.2\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[InstallDelete]
Type: filesandordirs; Name: "{app}\_internal\markdown-3.8.2.dist-info"

[UninstallDelete]
Type: filesandordirs; Name: "{userappdata}\ZHJ\FilesChecker3"
Type: dirifempty; Name: "{userappdata}\ZHJ"

[Icons]
Name: "{autoprograms}\{cm:MyAppName}"; Filename: "{app}\FilesChecker.exe"
Name: "{autodesktop}\{cm:MyAppName}"; Filename: "{app}\FilesChecker.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\FilesChecker.exe"; Parameters: "/Clean"; Description: "{cm:LaunchProgram,{cm:MyAppName}}"; Flags: nowait postinstall
