; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId=ZHJ_FilesChecker4
AppName={cm:MyAppName}
AppVersion=4.0.1
;AppVerName=FilesChecker 4.0.1
AppPublisher=ZHJ
AppPublisherURL=https://github.com/ZHJ00000/
AppSupportURL=https://github.com/ZHJ00000/FilesChecker/wiki
AppUpdatesURL=https://github.com/ZHJ00000/FilesChecker/releases
DefaultDirName={autopf}\FilesChecker4
UninstallDisplayIcon={app}\FilesChecker.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible and not arm64
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=LICENSE.txt
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=FilesCheckerSetup_4.0.1_amd64
Compression=lzma
SolidCompression=yes
WizardStyle=modern
AppCopyright=Copyright ©2026 ZHJ.
MinVersion=10.0.10240
VersionInfoCompany=ZHJ
VersionInfoDescription=FilesChecker
VersionInfoProductName=FilesChecker
VersionInfoVersion=4.0.1
UninstallDisplayName={cm:MyAppName}
PrivilegesRequiredOverridesAllowed=dialog

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
Name: "chinesetraditional"; MessagesFile: "compiler:Languages\ChineseTraditional.isl"

[CustomMessages]
english.MyAppName=FilesChecker
chinesesimplified.MyAppName=文件校验器
chinesetraditional.MyAppName=文件校驗器

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Source: "..\dist\FilesChecker\FilesChecker.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\dist\FilesChecker\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[UninstallDelete]
Type: filesandordirs; Name: "{userappdata}\ZHJ\FilesChecker3"
Type: dirifempty; Name: "{userappdata}\ZHJ"

[Icons]
Name: "{autoprograms}\{cm:MyAppName}"; Filename: "{app}\FilesChecker.exe"
Name: "{autodesktop}\{cm:MyAppName}"; Filename: "{app}\FilesChecker.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\FilesChecker.exe"; Description: "{cm:LaunchProgram,{cm:MyAppName}}"; Flags: nowait postinstall skipifsilent

[Code]
procedure CurStepChanged(CurStep: TSetupStep);
var
  SourceDir, TargetDir, UninstallString, UninstallKey: string;
  ResultCode: Integer;
begin
  SourceDir := ExpandConstant('{userappdata}\ZHJ\FilesChecker4')
  TargetDir := ExpandConstant('{userappdata}\ZHJ\Backup_FilesChecker4')
  UninstallString := ''
  UninstallKey := 'Software\Microsoft\Windows\CurrentVersion\Uninstall\ZHJ_FilesChecker4_is1';
  if RegQueryStringValue(HKLM, UninstallKey, 'UninstallString', UninstallString) or RegQueryStringValue(HKCU, UninstallKey, 'UninstallString', UninstallString) then
  begin
    UninstallString := RemoveQuotes(UninstallString);
  end;
  if CurStep = ssInstall then
  begin
    if DirExists(ExpandConstant('{userappdata}\ZHJ\FilesChecker4')) then
    begin
      // 安装前复制（示例路径，需根据实际情况修改）
      if not RenameFile(SourceDir, TargetDir) then 
      begin
        MsgBox(ExpandConstant('{cm:ErrorCreatingTemp}{userappdata}\ZHJ\Backup_FilesChecker4'), mbError, MB_OK);
        Abort; // 终止安装
      end;
    end;
    
    if FileExists(UninstallString) then
    begin
      if not Exec(UninstallString, '/SILENT', '', SW_SHOWNORMAL, ewWaitUntilTerminated, ResultCode) then
      begin
        MsgBox(ExpandConstant('{cm:UninstallError}'), mbError, MB_OK);
        Abort; // 终止安装
      end;
      Sleep(1000)
    end;
  end;
  if CurStep = ssPostInstall then
  begin
    if DirExists(ExpandConstant('{userappdata}\ZHJ\Backup_FilesChecker4')) then
    begin
      // 安装后复制（示例路径，需根据实际情况修改）
      if not RenameFile(TargetDir, SourceDir) then 
      begin
        MsgBox(ExpandConstant(ExpandConstant('{cm:ErrorCreatingTemp}{userappdata}\ZHJ\FilesChecker4')), mbError, MB_OK);
        Abort; // 终止安装
      end;
    end;
  end;
end;
